//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFromExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string Person { get; set; }
        public string Item { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
